name: ESP-IDF Build & Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        idf-version: [v6.0.0, latest]   
        target: [esp32]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache ESP-IDF
        uses: actions/cache@v4
        with:
          path: ~/.espressif
          key: esp-idf-${{ matrix.idf-version }}-${{ matrix.target }}-${{ runner.os }}-py3.13
          restore-keys: |
            esp-idf-${{ matrix.idf-version }}-
            esp-idf-

      - name: Configure target early
        run: echo "IDF_TARGET=${{ matrix.target }}" >> $GITHUB_ENV

      - name: Set up ESP-IDF (official espressif action)
        uses: espressif/esp-idf-action@v2
        with:
          esp-idf-version: ${{ matrix.idf-version }}
        env:
          IDF_TARGET: ${{ matrix.target }}

      - name: Verify ESP-IDF installation and export environment
        shell: bash
        run: |
          echo "IDF_PATH=${IDF_PATH:-<not-set>}"
          if [ -n "$IDF_PATH" ] && [ -f "$IDF_PATH/export.sh" ]; then
            echo "Sourcing $IDF_PATH/export.sh"
            . "$IDF_PATH/export.sh"
          else
            echo "ERROR: IDF_PATH or export.sh not found"
            env | sort
            exit 1
          fi
          which idf.py || true
          idf.py --version

      - name: Build firmware (Release)
        shell: bash
        run: |
          . "$IDF_PATH/export.sh"
          echo "Building for: IDF ${{ matrix.idf-version }} / Target $IDF_TARGET"
          idf.py build
        env:
          IDF_TARGET: ${{ matrix.target }}

      - name: Run unit tests (if defined)
        shell: bash
        run: |
          . "$IDF_PATH/export.sh"
          if idf.py test --list; then
            echo "Running available unit tests..."
            idf.py test
          else
            echo "No test targets defined — skipping."
          fi
        env:
          IDF_TARGET: ${{ matrix.target }}

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.idf-version }}-${{ matrix.target }}
          path: build/*.bin
